@startuml

skinparam monochrome true
skinparam classAttributeIconSize 0

class RestauranteRCCCF {
    - arbol : ArbolPedidos
    - cocinero : Cocinero
    + abrir()
}

class ArbolPedidos {
    - raiz : Nodo
    - comparaciones : int
    + insertar(p : Pedido)
    + sacarMinimo() : Pedido
}

class Nodo {
    - dato : Pedido
    - izq : Nodo
    - der : Nodo
}

class Cocinero {
    - actual : Pedido
    + trabajar()
}

class Pedido {
    - tiempo : int
    + restar()
}

RestauranteRCCCF *-- ArbolPedidos
RestauranteRCCCF *-- Cocinero
ArbolPedidos *-- Nodo
Nodo o-- Pedido
Cocinero --> Pedido
@enduml