@startuml DiagramaRCCCF

class Pedido {
  - id
  - tipo
  - tiempoPreparacion
  - tiempoRestante
  - minutoLlegada
}

class NodoPedido {
  - dato : Pedido
  - siguiente : NodoPedido
}

class ListaPedidos {
  - primero : NodoPedido
  - tamano
  + insertarAlFinal()
  + obtenerEn()
  + eliminarEn()
  + getTamano()
  + estaVacia()
}

class Cocina {
  - pedidosPendientes : ListaPedidos
  - pedidoEnCocina : Pedido
  - pedidosAtendidos
  - comparacionesSeleccion
  + anadirPedido()
  + seleccionarSiguientePedido()
  + procesarUnMinuto()
}

class SimulacionRCCCF {
  - generador
  - cocina
  - siguienteIdPedido
  - tiempoEsperaAcumulado
  + ejecutar()
}

SimulacionRCCCF --> Cocina
Cocina --> ListaPedidos
ListaPedidos --> NodoPedido
NodoPedido --> Pedido

@enduml